name: newapp_project
description: An e-commerce app for shirts.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  dio: ^4.0.0
  shared_preferences: ^2.0.8
  flutter_secure_storage: ^5.0.2
  cached_network_image: ^3.1.0
  flutter_svg: ^1.0.3
  google_fonts: ^2.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  flutter_lints: ^2.0.0 


flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/logo.png
